[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["Paul Min"]
edition = "2021"
license = "MIT"
repository = "https://github.com/paulusminus/transip"
rust-version = "1.68.2"
version = "0.3.0-dev.1"

[profile.release]
lto = true
opt-level = "z"
strip = true

