[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
authors = ["Paul Min"]
edition = "2024"
license = "MIT"
repository = "https://github.com/paulusminus/transip"
version = "0.4.2"

[profile.release]
lto = true
opt-level = "z"
strip = true
