[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["Paul Min"]
edition = "2021"
license = "MIT"
repository = "https://github.com/paulusminus/transip"
version = "0.1.2"

[profile.release]
lto = true
opt-level = "z"
strip = true

