[package]
edition.workspace = true
name = "transip-acme-dns-challenge"
version.workspace = true

[dependencies]
dns-check-updated = { path = "../dns-check-updated" }
tracing = "0.1"
tracing-journald = "0.3"
tracing-log = "0.1"
tracing-subscriber = "0.3"
transip-api = { path = "../transip-api" }
