[package]
name = "transip-acme-dns-challenge"
version = "0.3.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-journald = "0.3"
tracing-subscriber = "0.3"
transip-api = { path = "../transip-api" }
dns-check-updated = { path = "../dns-check-updated" }
