[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "dns-check-updated"
repository.workspace = true
version.workspace = true

[dependencies]
thiserror = "1"
tracing = "0.1"
trust-dns-resolver = "0.23"

[dev-dependencies]
tracing-subscriber = "0.3"