[package]
name = "http-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
http = "1.1.0"
http-body = "1.0.1"

[target.'cfg(not(all(target_family = "wasm", target_os = "wasi")))'.dependencies]
ureq = "2.10.1"

[target.'cfg(all(target_family = "wasm", target_os = "wasi"))'.dependencies]
waki = "0.3.1"
