[package]
name = "transip-api-ping"
edition.workspace = true
version.workspace = true

[dependencies]
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
transip-api = { version = "0.3.0", path = "../transip-api" }
