name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install extra packages
      run: |
        sudo apt update
        sudo apt install -y musl-tools
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy -- -D warnings
#    - name: Run tests
#      run: cargo test -p transip-api --verbose
    - name: Build for x86_64
      run: cargo build --verbose

